using DevExpress.XtraEditors;
using DevExpress.XtraEditors.Registrator;
using DevExpress.XtraGrid;
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.Entity;
using System.Drawing;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows.Forms;
using TMS.PL;

namespace TMS.PL
{
    public partial class FRM_USER : DevExpress.XtraEditors.XtraUserControl
    {
        // main var
        DBTMSEntities1 db;
        TB_Users users;
        FRM_USERS_ADD frm_add;
        public int id;
        public FRM_USER()
        {
            InitializeComponent();

            // This line of code is generated by Data Source Configuration Wizard
            // Instantiate a new DBContext
            TMS.DBTMSEntities1 dbContext = new TMS.DBTMSEntities1();
            // Call the LoadAsync method to asynchronously get the data for the given DbSet from the database.
            dbContext.TB_Users.LoadAsync().ContinueWith(loadTask =>
            {
                // Bind data to control when loading complete
                gridControl1.DataSource = dbContext.TB_Users.Local.ToBindingList();
            }, System.Threading.Tasks.TaskScheduler.FromCurrentSynchronizationContext());
        }

        private void gridControl1_Click(object sender, EventArgs e)
        {

        }

        // update data event
        private void btn_update_Click(object sender, EventArgs e)
        {
            UserDataUpdata();
        }
        public void UserDataUpdata()
        {
            try
            {
                db = new DBTMSEntities1();
                gridControl1.DataSource = db.TB_Users.ToList();
            }
            catch
            {
                MessageBox.Show("فقد الاتصال بقاعدة البيانات", "خطأ في الاتصال", MessageBoxButtons.OK, MessageBoxIcon.Warning);
            }

        }

        private void FRM_USER_Load(object sender, EventArgs e)
        {
            UserDataUpdata();
        }

        private void btn_add_Click(object sender, EventArgs e)
        {
            frm_add = new FRM_USERS_ADD();
            frm_add.id = 0;
            frm_add.btn_save.Text = "اضافة";
            frm_add.ShowDialog();
        }

        private void button1_Click(object sender, EventArgs e)
        {

            try
            {

                id = Convert.ToInt16(gridView1.GetFocusedRowCellValue("ID"));
                if (id == 0)
                {
                    MessageBox.Show("لا يوجد بيانات لتعديلها", "خطأ في عملية التعديل", MessageBoxButtons.OK, MessageBoxIcon.Warning);
                }
                else
                {
                    db = new DBTMSEntities1();
                    users = new TB_Users();
                    id = Convert.ToInt16(gridView1.GetFocusedRowCellValue("ID"));
                    users = db.TB_Users.Where(x => x.ID == id).FirstOrDefault();
                    frm_add = new FRM_USERS_ADD();
                    frm_add.id = id;
                    frm_add.btn_save.Text = "تعديل";
                    frm_add.edt_fullname.Text = users.FullName;
                    frm_add.edt_username.Text = users.UserName;
                    frm_add.edt_password.Text = users.Password;
                    frm_add.edt_roll.Text = users.Role;
                    frm_add.Show();
                }

            }
            catch
            {
                MessageBox.Show("فقد الاتصال بقاعدة البيانات", "خطأ في الاتصال", MessageBoxButtons.OK, MessageBoxIcon.Warning);
            }
        }

        private void btn_delete_Click(object sender, EventArgs e)
        {
            var rs = MessageBox.Show("هل انت متأكد من هذا الاجراء", "اجراء حذف", MessageBoxButtons.YesNo, MessageBoxIcon.Warning);
            if (rs == DialogResult.Yes)
            {
                try
                {

                    id = Convert.ToInt16(gridView1.GetFocusedRowCellValue("ID"));
                    if (id == 0)
                    {
                        MessageBox.Show("لا يوجد بيانات لحذفها", "خطأ في عملية الحذف", MessageBoxButtons.OK, MessageBoxIcon.Warning);
                    }
                    else
                    {
                        db = new DBTMSEntities1();
                        users = new TB_Users();
                        users = db.TB_Users.Where(x => x.ID == id).FirstOrDefault();
                        db.Entry(users).State = EntityState.Deleted;
                        db.SaveChanges();
                        toastNotificationsManager1.ShowNotification("638bf85f-6b40-485b-93eb-c022c4c18b3e");
                    }

                }
                catch
                {
                    MessageBox.Show("فقد الاتصال بقاعدة البيانات", "خطأ في الاتصال", MessageBoxButtons.OK, MessageBoxIcon.Warning);
                }
            }


        }
    }
}
